services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carlog-backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/app      # sincroniza el código
      - /app/node_modules           
    command: npm run dev            
